[project]
name = "unit-1"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "gymnasium[box2d]>=0.28.1",
    "huggingface-sb3>=3.0",
    "moviepy>=2.1.2",
    "pygame==2.1.3",
    "pyvirtualdisplay>=3.0",
    "stable-baselines3==2.0.0a5",
    "swig>=4.3.0",
]
